name: Delete PR Preview

on:
  issue_comment:
    types: [created]
jobs:
  delete:
    if: github.event.comment.body == '/delete'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Delete deployment directory
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git fetch
          git checkout gh-pages
          git rm -r "pr-${{ github.event.issue.number }}"
          git commit -m "Remove deployment preview for PR #${{ github.event.issue.number }}"
          git push origin gh-pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
