name: Flutter Web Preview

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    if: github.event.comment.body == '/preview'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Checkout PR
        if: github.event_name == 'issue_comment'
        run: gh pr checkout ${{ github.event.issue.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Repository
        id: version
        run: |
          REPOSITORY=$(echo ${{ github.repository }} | sed -e "s#.*/##")
          echo ::set-output name=repository::$REPOSITORY

      - name: Build Flutter web
        run: flutter build web --base-href /${{ steps.version.outputs.repository }}/${{ github.event.issue.number }}/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: ${{ github.event.issue.number }}
          publish_dir: build/web
          destination_dir: ${{ github.event.issue.number }}