name: Flutter Web Preview

on:
  issue_comment:
    types: [created]

permissions:
    contents: write
    issues: write
    pull-requests: write

jobs:
  build_and_deploy:
    if: github.event.comment.body == '/preview'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Install dependencies
      run: flutter pub get

    - name: Build Flutter web
      run: flutter build web

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/web

    - name: Post deployment comment
      run: |
        DEPLOYMENT_URL="https://${{ github.repository_owner }}.github.io/${{ github.repository }}"
        COMMENT_BODY="Preview URL: $DEPLOYMENT_URL"
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -X POST \
             -d "{\"body\": \"$COMMENT_BODY\"}" \
             "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
